"""Discoverable argument forms for the Commands panel.

Keep these aligned with the shared handlers and native Reup command flows.
A command can supply its own variants at registration to override this catalog.
"""

from __future__ import annotations

COMMAND_VARIANTS: dict[str, tuple[tuple[str, str], ...]] = {
    "/learn": (
        ("on", "Start learning mode; create baseline learn.md if missing."),
        ("off", "Return to normal agent behavior."),
        ("status", "Show your learning goal and current step."),
        ("setup", "Personalize preferences with guided questions and a file review."),
        ("init", "Create baseline learn.md without overwriting an existing file."),
        ("reload", "Load your latest edits to learn.md."),
        ("hint", "Ask for the next hint without replacement code."),
        ("review", "Ask iTE to review your attempt."),
    ),
    "/plan": (("on", "Enable plan mode."), ("off", "Disable plan mode.")),
    "/flow": (("status", "Show flow state."), ("setup", "Configure flow."),
              ("on", "Enable flow."), ("off", "Disable flow.")),
    "/goal": (("<objective>", "Create a goal."), ("pause", "Pause the goal."),
              ("resume", "Resume the goal."), ("edit <objective>", "Change the objective."),
              ("clear", "Clear the goal.")),
    "/attach": (("<path>", "Queue a file attachment."), ("--list", "List queued attachments."),
                ("--remove <index>", "Remove one attachment."), ("--clear", "Clear attachments.")),
    "/branch": (("<name>", "Switch branches."), ("--list", "List branches."),
                ("--create <name>", "Create and switch to a branch.")),
    "/publish": (("<remote-url>", "Publish using this remote URL."),
                 ("<remote-name> <remote-url>", "Publish using a named remote.")),
    "/hooks": (("on", "Enable configured hooks."), ("off", "Disable hooks.")),
    "/oi": (("on", "Enable Open Island notifications."), ("off", "Disable notifications.")),
    "/sessions": (("<session-id>", "Resume a saved session."), ("--list", "List sessions."),
                  ("--all", "Include sessions from other workspaces.")),
    "/compact": (("status", "Show context compaction status."),),
    "/rename": (("<name>", "Set the current session name."),),
    "/init": (("--force", "Regenerate an existing AGENTS.md."),),
    "/undo": (("--force", "Undo even when recorded files have changed since the operation."),),
    "/redo": (("--force", "Redo even when recorded files have changed since the operation."),),
    "/todos": (("planning on", "Show planning todos."), ("planning off", "Hide planning todos."),
               ("list [planning|execution]", "List all todos or one kind.")),
    "/subagent": (("list", "List available subagents."), ("create", "Create a subagent interactively."),
                  ("delete <name>", "Delete a subagent.")),
    "/skills": (("list", "List available skills."), ("help", "Show the skills guide."),
                ("show <name>", "Inspect a skill."), ("use <name>", "Activate a skill."),
                ("trust", "Trust skills provided by this workspace."), ("untrust", "Remove trust for workspace skills."),
                ("add <path|owner/repo|git-url> [--global|--local]", "Install a skill."),
                ("drop <name>", "Deactivate a skill."), ("clear", "Deactivate all skills.")),
    "/memory": (("prompt <query>", "Inspect memory selected for a prompt."),),
    "/aside": (("<question>", "Ask a transient side question."),),
    "/remote": (("on [port] [--local]", "Start the mobile remote bridge."),
                ("status", "Show bridge status."), ("code", "Show a pairing code."),
                ("devices", "List trusted devices."), ("revoke <device-id-prefix>", "Revoke a device."),
                ("revoke-all", "Revoke all devices."), ("off", "Stop the bridge.")),
    "/mcp": (
        ("list", "List configured MCP servers."), ("start <server>", "Start a server."),
        ("stop <server>", "Stop a server."), ("reset <server>", "Reset a server."),
        ("add <server> [--scope global|workspace]", "Add a server interactively."),
        ("doctor <server>", "Diagnose a server."),
        ("env list [server]", "List configured environment variable names."),
        ("env where <server>", "Show environment configuration locations."),
        ("env set <server> <KEY> <VALUE> [--scope global|workspace]", "Set an environment variable."),
        ("env import <server> <KEY> [PROCESS_ENV_NAME] [--scope global|workspace]", "Import a process environment variable."),
        ("env unset <server> <KEY> [--scope global|workspace]", "Remove an environment variable."),
    ),
}
